WIP: Fixing deprecations for Shapely 2.0, Numpy and Pyproj
oscarpilote/Ortho4XP pull request #186
Opened 2023-01-07 08:29 UTC by ekaats

I have been adding some fixes to support Shapely 2.0 and fix some future deprecations around pyproj and numpy.

There is still some weird stuff going on, particularly with providers that don't use 3857. I've mostly been testing with PDOK (Netherlands) as a provider, which does use 3857, but used the non-standard routine anyway. I fixed that, but need to do more testing with non-standard providers.

It takes some time to figure out if these are regressions or not.

2023-01-08 12:39 UTC, ekaats commented
Couldn't reproduce the earlier issues. Tested with PDOK and global providers and I don't get any errors.

I do realise I changed out the Nvidia converter for Imagemagick, at least for Linux. I couldn't find the library for my distro and a short search told me that it is not supported anymore. I'll leave it to someone else to decide if that is a welcome change.

2023-01-17 07:52 UTC, anthraxn8b commented
Good idea to introduce the "build" directory!

2023-01-17 08:52 UTC, anthraxn8b commented
Added my PR on top of @ekaats fork: https://github.com/ekaats/Ortho4XP/pull/1

2023-01-17 15:50 UTC, anthraxn8b commented
@ekaats, after reading though the issues I found out, that some people tried/try(?) to make a community software out of this. Maybe it would make sense to do the same work again in the community product?
https://github.com/Ortho4XP/Ortho4XP (in the DEV branch!)

2023-07-19 19:50 UTC, kyuknis commented
Tried it today and it seems mostly good to go. I moved all the tile directories over but where are the overlays to move into custom scenery?

2023-07-19 20:10 UTC, d41k4n commented
> where are the overlays to move into custom scenery?

Overlays are extracted into folder "yOrtho4XP_Overlays" within the Ortho4XP home folder. Btw. the official support forum is located [here](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/).

2023-08-15 17:01 UTC, w8sl approved these changes
Brilliant update - thank You!

2023-08-24 08:14 UTC, jonaseberle commented
Now that we have a `requirement.txt` this Pull Request would just need to update it.

I am happy to test. Any region/provider to look out for?

2023-08-24 18:17 UTC, w8sl commented
EPSG3857 The most common CRS for online maps, used by almost all free and commercial tile providers ?

2023-08-24 18:55 UTC, d41k4n requested changes
Probably better to use the existing vprint function for debug logging to be more consistent.

2023-08-24 18:55 UTC, d41k4n commented on src/O4_Imagery_Utils.py
> +            print("works")
```suggestion
            UI.vprint(3,"works")
```

2023-08-24 18:55 UTC, d41k4n commented on src/O4_Imagery_Utils.py
> +            print("division by zero at build_texture_from_bbox_and_size")
```suggestion
            UI.vprint(3,"division by zero at build_texture_from_bbox_and_size")
```

2023-08-24 20:32 UTC, d41k4n commented
@jonaseberle 
> Now that we have a `requirement.txt` this Pull Request would just need to update it.

I'd suggest to either rebase this branch on the latest master or merge first and then update the requirements.txt with a separate PR.

2023-08-25 07:17 UTC, jonaseberle commented
@d41k4n both is fine, thanks for taking care.

2023-08-26 09:54 UTC, w8sl requested changes
Coordinates for non EPSG3857 providers are wrong.
Fix:
line 26 in src/04_GEO_Utils.py:
return Transformer.from_crs(crs_from=f"EPSG:{s_epsg}", crs_to=f"EPSG:{t_epsg}", always_xy=True).transform(s_x, s_y)

2023-08-26 11:06 UTC, d41k4n requested changes

2023-08-26 11:06 UTC, d41k4n commented on src/O4_Geo_Utils.py
> +    return Transformer.from_crs(crs_from=f"EPSG:{s_epsg}", crs_to=f"EPSG:{t_epsg}").transform(s_x, s_y)
As per @w8sl 's suggestion:
```suggestion
    return Transformer.from_crs(crs_from=f"EPSG:{s_epsg}", crs_to=f"EPSG:{t_epsg}", always_xy=True).transform(s_x, s_y)
```

2023-10-06 11:48 UTC, w8sl requested changes
Fix for deprecation affecting road_level>2:
Line 200 in 04_Vector_Utils.py:
`    road_network_banked=geometry.MultiLineString(list(road_network_banked.geoms)+list(road_network_banked_2.geoms))`

2023-10-14 16:42 UTC, w8sl commented on src/O4_File_Names.py
> +Tmp_dir = os.path.join(Ortho4XP_dir, build_dir, "tmp")
"tmp" seems to be hardcoded to main folder. Exotic stuff like "imprint_masks_to_dds" but still.

Tmp_dir       =  os.path.join(Ortho4XP_dir, 'tmp')

2024-02-11 14:28 UTC, merged